name: Processor Checklist
description: inspect and clean the processor
title: "[MAINTENANCE]: "
labels: ["hanscom"]
projects: ["cosmic_owl"]
assignees:
  - bbashor

body:

  - type: input
    id: pdr_number
    attributes:
      label: PDR Number
      description: What PDR is this?
      placeholder: PDR000AF
    validations:
      required: true

  - type: input
    id: serial_number
    attributes:
      label: Serial Number
      description: What is the processor serial number?
      placeholder: xxxxxxx
    validations:
      required: true

  - type: textarea
    id: arrival_condition
    attributes:
        label: External damage or tampering
        description: Note and physical damage to the processor
        placeholder: Normal wear and tear.

  - type: textarea
    id: before_pictures
    attributes:
      label: Arrival Photos
      description: Take photos of the processor, include a few with the top cover removed.  Also, take a picture with the disk bays open to show the disk.  This is to provide evidence when Dan said you had the disk and you can't remember if you did or not.
      placeholder: attach photos here.
  
  - type: markdown
    attributes:
      value: |
        ## Power Off

        The following steps are to be performed with the processor powered off.

  - type: checkboxes
    id: reset_connections
    attributes:
      label: Internal Connection(s) reset
      description: Remove and reinsert the following connectors.
      options:
        - label: Main motherboard buss
        - label: FAN1 CPU fan
        - label: FAN2 external fan
        - label: FAN5 external fan
        - label: 4PIN
        - label: 8PIN
        - label: DVD power and SATA
        - label: Bay 0 power and SATA
        - label: Bay 1 power and SATA
        - label: Back fans
        - label: Front fans
        - label: CPU fans

  - type: checkboxes
    id: bay_doors
    attributes:
      label: Bay Doors
      description: Check the ethernet ports by plugging in an ethernet cable into the nic and perform a basic ping test.
      options:
        - label: left door
        - label: right door

